name: "Login Azure CLI"
description: "Login Azure CLI"

inputs:
  username:
    required: true
    type: string
  password:
    required: true
    type: string
  tenant:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Login Azure CLI
      shell: bash
      run: |
        az login \
          --service-principal \
          --username "${{ inputs.username }}" \
          --password "${{ inputs.password }}" \
          --tenant "${{ inputs.tenant }}"
