# Generated by Django 3.2.8 on 2021-10-31 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tfa_last_code",
            field=models.CharField(
                blank=True, max_length=6, verbose_name="TFA last code"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="tfa_secret",
            field=models.CharField(
                blank=True, max_length=32, verbose_name="TFA secret"
            ),
        ),
    ]
