name: "Install Google Cloud CLI"
description: "Install Google Cloud CLI"

inputs:
  version:
    required: false
    type: string
    default: "480.0.0"

runs:
  using: "composite"
  steps:
    - name: Install Google Cloud CLI
      shell: bash
      run: |
        export PATH=$HOME/gcp/bin:$PATH
        export USE_GKE_GCLOUD_AUTH_PLUGIN=True
        wget https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-${{ inputs.version }}-linux-x86_64.tar.gz -O cli.tar.gz
        tar -xf cli.tar.gz
        rm cli.tar.gz
        mv google-cloud-sdk $HOME/gcp
        gcloud components install gke-gcloud-auth-plugin kubectl
