name: "Build Docker image"
description: "Build Docker image"

inputs:
  tag:
    required: false
    default: "app:1.0"
    type: string

runs:
  using: "composite"
  steps:
    - name: Build Docker image ${{ inputs.tag }}
      shell: bash
      run: |
        echo "Building Docker image... ${{ inputs.tag }}"
