name: "Install Azure CLI"
description: "Install Azure CLI"

inputs:
  version:
    required: false
    type: string

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
    - name: Install Azure CLI
      shell: bash
      run: |
        python -m pip install -U pip
        [ -n "${{ inputs.version }}" ] && \
          python -m pip install azure-cli==${{ inputs.version }} || \
          python -m pip install azure-cli
