name: "Install Azure CLI"
description: "Install Azure CLI"

runs:
  using: "composite"
  steps:
    - name: Install Azure CLI
      shell: bash
      run: |
        python -m pip install -U pip
        python -m pip install azure-cli==2.61.0
