name: "Set Docker image to ContainerApp deployment"
description: "Set Docker image to ContainerApp deployment"

inputs:
  containerapp-resource-group:
    required: true
    type: string
  containerapp-name:
    required: true
    type: string
  acr-name:
    required: true
    type: string
  acr-image-tag:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Set Docker image to ContainerApp deployment
      shell: bash
      run: |
        az containerapp update \
          --name ${{ inputs.containerapp-name }} \
          --resource-group ${{ inputs.containerapp-resource-group }} \
          --image ${{ inputs.acr-name }}.azurecr.io/${{ inputs.acr-image-tag }}
