name: "Login Google Cloud CLI"
description: "Login Google Cloud CLI"

inputs:
  project:
    required: true
    type: string
  b64-credentials:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Login Google Cloud CLI
      shell: bash
      run: |
        echo -n "${{ inputs.b64-credentials }}" | base64 -d >/tmp/gcp.json
        sdk/bin/gcloud auth activate-service-account --key-file /tmp/gcp.json
        sdk/bin/gcloud config set project "${{ inputs.project }}"
