name: Django app template

on:
  push:
    branches:
      - main
      - staging
      - develop
  pull_request:
    branches:
      - main
      - staging
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Docker image
      run: |
        docker image build --tag dj:1.0 .
    - name: Test Docker image
      run: |
        docker container run --rm --env ENV="test" dj:1.0
