name: App

on:
  push:
    branches:
      - main
      - staging
      - develop
  pull_request:
    branches:
      - main
      - staging
      - develop

jobs:
  build:
    # if: ${{ github.ref }} != "refs/heads/abc"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checjout
      - uses: ./.github/workflows/build-docker-image.yml
        name: Build Docker image
        with:
          tag: "dj:2.0"
      - name: Test Docker image
        run: |
          docker container run --rm --env ENV="test" dj:2.0
