name: App

on:
  push:
    branches:
      - main
      - staging
      - develop
  pull_request:
    branches:
      - main
      - staging
      - develop

jobs:
  build-and-test-image:
    if: ${{ github.ref }} == "refs/heads/main"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-docker-image
        with:
          tag: "app:1.0"
      - uses: ./.github/actions/test-docker-image
        with:
          tag: "app:1.0"
      - uses: ./.github/actions/az-install
      - uses: ./.github/actions/az-login
        with:
          username: ${{ secrets.AZ_USERNAME }}
          password: ${{ secrets.AZ_PASSWORD }}
          tenant: ${{ secrets.AZ_TENANT }}
