name: Deploy

on:
  workflow_call:
    inputs:
      image-tag:
        required: true
        type: string
      gcp-project:
        required: true
        type: string
      ar-name:
        required: true
        type: string
      ar-repository:
        required: true
        type: string
      gke-cluster:
        required: true
        type: string
      gke-zone:
        required: true
        type: string
      gke-deployment:
        required: true
        type: string
      gke-container:
        required: true
        type: string
    secrets:
      gcp-b64-credentials:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/docker-build-image
        with:
          image-tag: ${{ inputs.image-tag }}
      - uses: ./.github/actions/docker-test-image
        with:
          image-tag: ${{ inputs.image-tag }}
      - uses: ./.github/actions/gcp-install
      - uses: ./.github/actions/gcp-login
        with:
          project: ${{ inputs.gcp-project }}
          b64-credentials: ${{ secrets.gcp-b64-credentials }}
      - uses: ./.github/actions/gcp-ar-push-image
        with:
          ar-image-tag: ${{ inputs.image-tag }}
          ar-name: ${{ inputs.ar-name }}
          ar-project: ${{ inputs.gcp-project }}
          ar-repository: ${{ inputs.ar-repository }}
      - uses: ./.github/actions/gcp-gke-set-image
        with:
          ar-image-tag: ${{ inputs.image-tag }}
          ar-name: ${{ inputs.ar-name }}
          ar-project: ${{ inputs.gcp-project }}
          ar-repository: ${{ inputs.ar-repository }}
          gke-cluster: ${{ inputs.gke-cluster }}
          gke-zone: ${{ inputs.gke-zone }}
          gke-deployment: ${{ inputs.gke-deployment }}
          gke-container: ${{ inputs.gke-container }}
