name: App

on:
  push:
    branches:
      - main
      - staging
      - develop
  pull_request:
    branches:
      - main
      - staging
      - develop

jobs:
  deploy-main:
    if: ${{ github.ref }} == "refs/heads/main"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/docker-build-image
        with:
          tag: "app:1.0"
      - uses: ./.github/actions/docker-test-image
        with:
          tag: "app:1.0"
      - uses: ./.github/actions/az-install
      - uses: ./.github/actions/az-login
        with:
          username: ${{ secrets.AZ_USERNAME }}
          password: ${{ secrets.AZ_PASSWORD }}
          tenant: ${{ secrets.AZ_TENANT }}
      - uses: ./.github/actions/az-acr-push-image
        with:
          acr-name: "conapi3bmicroservice"
          acr-image-tag: "app:1.0"
      - uses: ./.github/actions/az-containerapp-set-image
        with:
          containerapp-resource-group: "DEVOP"
          containerapp-name: "app"
          acr-name: "conapi3bmicroservice"
          acr-image-tag: "app:1.0"
