name: Workflow

on:
  push:
    branches:
      - develop
      - staging
      - main
  pull_request:
    branches:
      - develop
      - staging
      - main

jobs:
  develop:
    if: github.ref == 'refs/heads/develop'
    uses: ./.github/workflows/deploy.yml
    with:
      image-tag: app-dev:${{ github.sha }}
      gcp-project: ${{ vars.DEVELOP_GCP_PROJECT }}
      ar-name: ${{ vars.DEVELOP_AR_NAME }}
      ar-repository: ${{ vars.DEVELOP_AR_REPOSITORY }}
      gke-cluster: ${{ vars.DEVELOP_GKE_CLUSTER }}
      gke-zone: ${{ vars.DEVELOP_GKE_ZONE }}
      gke-deployment: ${{ vars.DEVELOP_GKE_DEPLOYMENT }}
      gke-container: ${{ vars.DEVELOP_GKE_CONTAINER }}
    secrets:
      gcp-b64-credentials: ${{ secrets.DEVELOP_GCP_B64_CREDENTIALS }}
  staging:
    if: github.ref == 'refs/heads/staging'
    uses: ./.github/workflows/deploy.yml
    with:
      image-tag: app-dev:${{ github.sha }}
      gcp-project: ${{ vars.STAGING_GCP_PROJECT }}
      ar-name: ${{ vars.STAGING_AR_NAME }}
      ar-repository: ${{ vars.STAGING_AR_REPOSITORY }}
      gke-cluster: ${{ vars.STAGING_GKE_CLUSTER }}
      gke-zone: ${{ vars.STAGING_GKE_ZONE }}
      gke-deployment: ${{ vars.STAGING_GKE_DEPLOYMENT }}
      gke-container: ${{ vars.STAGING_GKE_CONTAINER }}
    secrets:
      gcp-b64-credentials: ${{ secrets.STAGING_GCP_B64_CREDENTIALS }}
  main:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yml
    with:
      image-tag: app-dev:${{ github.sha }}
      gcp-project: ${{ vars.MAIN_GCP_PROJECT }}
      ar-name: ${{ vars.MAIN_AR_NAME }}
      ar-repository: ${{ vars.MAIN_AR_REPOSITORY }}
      gke-cluster: ${{ vars.MAIN_GKE_CLUSTER }}
      gke-zone: ${{ vars.MAIN_GKE_ZONE }}
      gke-deployment: ${{ vars.MAIN_GKE_DEPLOYMENT }}
      gke-container: ${{ vars.MAIN_GKE_CONTAINER }}
    secrets:
      gcp-b64-credentials: ${{ secrets.MAIN_GCP_B64_CREDENTIALS }}
